### PR TITLE
Add AWS AMI Exists check to External Checks Registry

### PR DESCRIPTION
**Pull request by mtougeron**

### CODE REVIEW

**Comment by joshulyne** [comment]
@mtougeron Thanks so much for contributing this! Tested this locally in our k8s cluster and it worked well!! @jonnydawg looking for your review since you contributed the original ami check but this looks GREAT to me!! 🎉

**Comment by mtougeron** [comment]
> Tested this locally in our k8s cluster and it worked well!!

That's great! Hopefully this will be useful for folks who are not using kops

**Review by joshulyne — APPROVED** [review]

**Comment by integrii** [comment]
This rocks!

**Review by integrii — APPROVED** [review]

**Comment by mtougeron** [comment]
thanks!

**Pull request merged**
