### PR TITLE
fix goroutine leak in watchForCheckerPodShutdown()

### LINKED ISSUE #533: Possible goroutines leak from watch events
**Describe the bug**
Memory consumption of the kuberhealthy deployment increases steadily when running inside a cluster performing several checks. We deployed kuberhealthy together with a daemonset-, dns-name-resolution- and network-connection-check into muliple clusters. We set a memory limit to 50Mi via Kubernetes resources. Thereby a pattern emerged that the main kuberhealthy server deployment was OOM killed after about 2 days. Following shows the graphs for the `container_memory_usage_bytes` prometheus metric coming from cadvisor. Left are clusters with the limit set to 50Mi, on the right there are clusters where the memory limit is removed:

kuberhealthy01
 
By that I assume that the memory consumption would rise indefinitely.

After adding pprof to kuberhealty and looking at the goroutines graph you can see that an increasing number of goroutines are put into waiting state at `runtime.gopark` as they seem to block/wait at the `receive` method of apimachinery's `StreamWatcher`:
```
goroutine 2486 [chan send, 143 minutes]:
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0004e0700)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:127 +0x15b
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:71 +0xbe
```

Here the corresponding graph:

kuberhealthy-goroutines

**Steps To Reproduce**
- Let kuberhealthy run freely over a certain amount of time with several checks

**Expected behavior**
That kuberhealthy does not continuously accumulate goroutines during its runtime.

**Versions**
 - Cluster OS: `5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Kubernetes Version: `v1.17.6`
 - Kuberhealthy Release: `v2.2.0`

**Additional context**

I tried to pinpoint where the problem occurs but my unfamiliarity with the code I did not yet succeed. Perhaps someone with more knowledge might chime in. 
My first guess was following lines: https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/kuberhealthy/kuberhealthy.go#L162

The `watchForKHCheckChanges` creates a watcher (https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/kuberhealthy/kuberhealthy.go#L282) which internally writes `Events` to a unbuffered channel. Those Events are processes and new Signals are written to another unbuffered channel (https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/kuberhealthy/kuberhealthy.go#L297). But then the `notifyChanLimiter` and the `monitorExternalChecks` work with a buffered channel that is processed every 10 seconds (https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/kuberhealthy/util.go#L47). So it might be that the Watch writes Events into the unbuffered channel for an goroutines pile up processing those. But this is all just a theory and probably totally wrong :).

### PR DESCRIPTION
**Pull request by sbueringer**
Fixes #533

I fixed the leak on a heavily modified branch wit logging of goroutine ids including who creates which goroutine etc. This is the change which finally fixed the leak. I'm currently verifying that this version without all other changes also fixes the leak.

### CODE REVIEW

**Comment by sbueringer** [comment]
@integrii Could it be that you dropped the capability to set the kubecfg on master? We used that with the 2.2.0 version. I saw that the flag was removed and that there's a property in the config file. But I'm not sure how to use that as it's a unexported variable and therefore not parsed? Looks to me like I have to overwrite the HOME var in my Pod and put the kubeconfig under $HOME/.kube/config?

**Comment by integrii** [comment]
Ah yeah. The new `$KUBECONFIG` env var should work.  I can test sometime soon... This is part of the new configmap and live reloading that was just merged to master today.  It's still due for some more testing before it gets into a release...

**Comment by integrii** [comment]
By the way, I plan to review and test this PR Monday... I really appreciate your debugging so carefully to find root cause.  Awesome!

**Comment by sbueringer** [comment]
> Ah yeah. The new `$KUBECONFIG` env var should work. I can test sometime soon... This is part of the new configmap and live reloading that was just merged to master today. It's still due for some more testing before it gets into a release...

Ah thx. Mounting it at ~/.kube/config also worked :)

**Comment by sbueringer** [comment]
> By the way, I plan to review and test this PR Monday... I really appreciate your debugging so carefully to find root cause. Awesome!

Thx, no problem :). Looks like it works in my env still 6Mi memory usage after 6 hours. Usually it was already higher at this point. Btw I assume the goroutine leak is a race condition which is not always triggered, e.g. when I run kuberhealthy outside the cluster in my IDE I cannot reproduce it.

**Comment by cagdascirit** [comment]
@sbueringer @integrii I have patched v2.2.0 with this commit and the memory leak problem has been resolved in our test environment. For 10+ hours memory consumption kept steady

**Comment by integrii** [comment]
Thanks for testing guys. I have a branch I'm going to PR tomorrow that has a slightly different take on this. Instead of emptying the channel, we leave the for loop running until the range breaks due to a closed channel. This ensures that the channel is always emptied. 

I also chased down a couple other missing channel closes that were needed and simplified the retry logic...

**Comment by sbueringer** [comment]
> Thanks for testing guys. I have a branch I'm going to PR tomorrow that has a slightly different take on this. Instead of emptying the channel, we leave the for loop running until the range breaks due to a closed channel. This ensures that the channel is always emptied.
> 
> I also chased down a couple other missing channel closes that were needed and simplified the retry logic...

Yup sure, sgtm. I'm aware my "solution" is just a quick hack but doesn't solve the underlying problem (that the consumer of the streamwatcher is terminated before stop is called)

**Comment by integrii** [comment]
I have refactored this in the branch `pr-fix-goroutine-leak` (bc22bd1) here and am testing locally before opening a PR...  This fix includes a refactor to the channel handling.  To solve the problem identified in this thread, the reader of the watch channel does not stop reading until the channel is closed, but to prevent an upstream blockage, only writes one message back to the original caller.

This branch also includes a bunch of other readability and simplification...

**Comment by integrii** [comment]
Feel free to test this build while I am working on getting a suitable test environment handy: `docker pull kuberhealthy/kuberhealthy:537`

**Comment by integrii** [comment]
Remember to apply this yaml configmap now that configmap support is in master... Be sure to use the updated `deployment` and `configmap` from [this spec](https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml)

**Comment by integrii** [comment]
I've got metrics on this now... I'll let you guys know how it looks in a day.

image

**Comment by integrii** [comment]
Memory is looking good!  This is the master pod:
image

Here is the secondary pod. looks like it's hardly using any memory:
image

**Comment by cagdascirit** [comment]
@integrii which branch we can use to collect the fixes?

**Comment by sbueringer** [comment]
@integrii When there's another PR ready which fixes this, I'm happy to close this PR and test your fix in our env. For now, I'm not really in a hurry as we're using my patch from this PR in production and it looks fine.

**Comment by integrii** [comment]
Checked today and this memory leak is still there on my branch it looks like.  I will revisit soon.

image

**Pull request merged**
