### PR TITLE
apiGroup typo

### PR DESCRIPTION
**Pull request by integrii**
- fixes typo in helm chart that causes incorrect RBAC on daemonset checker

### CODE REVIEW

**Comment by qqshfox** [comment]
Tested locally and this worked for me as well.

**Comment by zeleena** [comment]
This works for the helm chart but ideally this should be changed everywhere this is mentioned, and the typo still exists in the following flat files:

- https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml#L216
- https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy-prometheus.yaml#L246
- https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy-prometheus-operator.yaml#L246

**Comment by joshulyne** [comment]
also, could we get rid of the apigroup "extensions" now?

**Comment by integrii** [comment]
I am going to attempt to add a trigger for github to rebuild the flat files on each master merge...

**Comment by integrii** [comment]
For now, lets merge this.  Then, lets regen the flat files.  The automatic flat file regen github action is ready for initial tests in #327

**Comment by integrii** [comment]
@joshulyne I don't think we can drop the `extensions` api version yet.  

The Kubernetes 1.11 documentation still lists custom resources as using it:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#customresourcedefinition-v1beta1-apiextensions-k8s-io

**Pull request merged**
