### PR TITLE
Fix strings in static yamls

### PR DESCRIPTION
**Pull request by integrii**
Fixing #163

### CODE REVIEW

**Comment by ihoegen-isp** [comment]
I don't think those environment variables are even being used, they're supposed to be flags. Can you verify?

**Comment by integrii** [comment]
If they aren't, they will be.  I think @joshulyne was working on adding check on/off flags

**Comment by ihoegen** [comment]
Were check on/off going to be used as flags or environment variables?

**Comment by integrii** [comment]
Both.  Fixed in #165 
Precedence is: flag, env var, default

**Comment by integrii** [comment]
@ihoegen PR plz :-D

**Pull request merged**
